### ISSUE TITLE
Überschriften im Dashboard

### ISSUE THREAD

**Issue by MarcusBaumgarten** [ediarum/ediarum.DB#1]
Nach dem Update auf 3.2.5 kann man im Dashboard in der Ediarum-Verwaltung keine Überschriften mehr lesen.

**Comment by MartinFechner** [comment]
Lieber @MarcusBaumgarten , wir sind gerade dabei die App für eXist 5 fit zu machen. Falls das Problem noch besteht, kannst Du mir bitte mehr Informationen schicken?

**Comment by MartinFechner** [comment]
Lieber @MarcusBaumgarten , kannst Du bitte schauen, ob das Problem mit der neuesten Version <https://github.com/ediarum/ediarum.DB/releases/tag/v4.0.1> immer noch besteht und falls ja mir bitte einen Screenshot schicken?
