### ISSUE TITLE
HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException:

### ISSUE THREAD

**Issue by ogierMontanus** [ediarum/ediarum.DB#11]
I get the following error when running ediarium.DB on a freshly installed eXistDB 5.2. I have next to no eXist-experience, so I do not know how to manually correct the notation ':=' in the config module. Any help is much appriciated. Kind regards from Odense, Denmark, Holger Berg

URI: | /exist/apps/ediarum/
-- | --
500
javax.servlet.ServletException:  javax.servlet.ServletException: An error occurred while processing  request to /exist/apps/ediarum/: err:XPST0003 error found while loading  module config: Error while loading module modules/config.xqm: The ':='  notation is no longer accepted in map expressions: use ':' instead. [at  line 1234, column 24]
XQueryURLRewrite
javax.servlet.ServletException:  javax.servlet.ServletException: An error occurred while processing  request to /exist/apps/ediarum/: err:XPST0003 error found while loading  module config: Error while loading module modules/config.xqm: The ':='  notation is no longer accepted in map expressions: use ':' instead. [at  line 1234, column 24]
javax.servlet.ServletException: An error  occurred while processing request to /exist/apps/ediarum/: err:XPST0003  error found while loading module config: Error while loading module  modules/config.xqm: The ':=' notation is no longer accepted in map  expressions: use ':' instead. [at line 1234, column 24]
org.exist.xquery.XPathException: err:XPST0003  error found while loading module config: Error while loading module  modules/config.xqm: The ':=' notation is no longer accepted in map  expressions: use ':' instead. [at line 1234, column 24]

**Comment by ksbbf** [comment]
If i remember correctly, i had this exception either.

The ediarum-docs recommend eXist 3.5 or 4.4, so I switched to an exist-Version minor than 5. 

There are a lot of more issues, which are to be solved to make ediarum compatible with exit 5.x - such as http-libs.

If you want to save time and start immediately with ediarum, install exist 4.4.

**Comment by StefanDumont** [comment]
Yeah, @ksbbf is right. At the moment eXistdb isn't compatible with eXistdb 5. We have planned to migrate ediarum.DB to eXistdb 5 this winter. Perhaps we can release the new version in January ...

**Comment by ogierMontanus** [comment]
Dear Stefan Dumont, dear ksbbf. Thanks for the swift replies. I will give it a go with existDB 4.4. Ediarium seems like a very promising solution, so your effort is much appreciated.

Fra: Stefan Dumont <notifications@github.com>
Sendt: 23. november 2020 19:15
Til: ediarum/ediarum.DB <ediarum.DB@noreply.github.com>
Cc: Nils Holger Németh Berg <nh@sdu.dk>; Author <author@noreply.github.com>
Emne: Re: [ediarum/ediarum.DB] HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: (#11)


Yeah, @ksbbf<https://github.com/ksbbf> is right. At the moment eXistdb isn't compatible with eXistdb 5. We have planned to migrate ediarum.DB to eXistdb 5 this winter. Perhaps we can release the new version in January ...

**Comment by MartinFechner** [comment]
Dear @rowissmann , we have a new release candidate which supports eXist 5. If you want to test it please write me a mail (fechner@bbaw.de). We plan to publish the new version in May 2021.

**Comment by ogierMontanus** [comment]
Dear @MartinFechner and @rowissmann: heads up regarding the update. I look forward to the May release. Beste Gruesse aus Odense/Daenemark, Holger Berg

**Comment by MartinFechner** [comment]
Dear @ogierMontanus , thanks for using ediarum.DB ! We do our very best to support digital editions with our solutions.

**Comment by MartinFechner** [comment]
@ogierMontanus As you have surely seen we have published a new version of ediarum.DB <https://github.com/ediarum/ediarum.DB/releases/tag/v4.0.1>.
