### ISSUE TITLE
Incompatible with eXist-db 5.3.0 / functx-1.0.1

### ISSUE THREAD

**Issue by nberns** [ediarum/ediarum.DB#15]
Hallo,
zuallererst ediarum ist ein super Projekt!
Beim Öffnen von ediarum.DB tritt leider ein Konflikt mit functx auf, welches notwendig für die aktuelle Version von eXist ist.
Fehlermeldung:

> /db/apps/ediarum/modules/view.xqlerr:XQST0034 error found while loading module project-pages: Error while loading module ../controllers/project-pages-controller.xql: Prolog has imports a module that defines a function which is already defined in the importing module: {http://www.functx.com}escape-for-regex#1 [at line 8, column 41]

Ausweichen auf 5.2.0 funktioniert.
Viele Grüße

**Comment by MartinFechner** [comment]
Danke, das Problem wurde mit dem letzten Release gelöst.
