### ISSUE TITLE
Übergabe des Felds “key” aus Zotero in ID klappt nicht immer

### ISSUE THREAD

**Issue by jjarosch** [ediarum/ediarum.DB#5]
An dieser Stelle wird das Element `<key>` nicht immer korrekt aufgerufen:
https://github.com/ediarum/ediarum.DB/blob/067f36adb92f0d0d6b63e0e141b9276f16fe7d9b/modules/config.xqm#L275

Ergebnis ist, dass der key nicht in die ID eingefügt und an die Schnittstelle weitergegeben wird, und in Oxygen dann z.B. `<item xml:id="zotero-2065617-">` zur Auswahl steht. Nutzerseitig gibt es also keine Fehlermeldung.

Irgendwie scheint es abhängig, wann  (?) die letzte Zotero-Synchronisation durchgeführt wurde. Manchmal sind nur ein Teil der Einträge betroffen, obwohl ihr XML in der eXist-db identisch aufgebaut ist. Nach Synchronisation sind dann alle betroffen.

Mein Workaround:
```
let $key := $item/*[name()='key']/string()
```

ediarum.DB Version 3.2.4.444, eXist-db Version 3.6.0

**Comment by MartinFechner** [comment]
So wie Du es beschreibts, scheint es ein Namespace-Problem zu sein. Jedenfalls spricht Dein Workaround hierfür. Ich glaube, etwa ähnliches (XQuery mit XPath und Namespace) ist mir auch schonmal vorgekommen. Könnte das an der eXist Version liegen?

**Comment by jjarosch** [comment]
Ich weiß bisher nicht, ob die eXist-Version etwas ausmacht, und habe im Moment keine verschiedenen Versionen zum Testen zur Hand. Abgesehen davon kriege ich es ja nicht mal verlässlich repliziert, weil ich nicht rausgefunden habe, wann / aus welchem Grund es auftritt.

Ich hatte gedacht, dass es vielleicht das Problem komplett umgehen und insgesamt robuster machen würde, die Zotero-Einträge mit einem (nicht-leeren) Namespace zu versehen?

**Comment by MartinFechner** [comment]
Nach unserer letzten Besprechung gehe ich davon aus, dass etwas mit der konkreten Datenbankinstanz nicht stimmt. Es könnte zum Beispiel der Index kaputt sein.

**Comment by jjarosch** [comment]
Ja, reindexieren hat das Problem behoben. Auch nach einer erneuten Synchronisation tritt es im Moment nicht wieder auf.
